name: Scrape website

on:
  push:
    branches: 
      - main
  schedule:     
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scrape-website:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 
      
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build docker image
        run: docker build -t scrape-norli .

      - name: Scrape websites with container
        run: docker run -v $PWD/output:/output scrape-norli

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4